tweak abstract and intro
danwing/signaling-use-cases pull request #13
Opened 2024-03-13 02:59 UTC by danwing

2024-03-13 06:37 UTC, boucadair requested changes

2024-03-13 06:37 UTC, boucadair commented on draft-rwbr-tsvwg-signaling-use-cases.md
> +to enable different traffic treatment for packets sent to the
```suggestion
to enable differentiated traffic treatment for packets sent to the
```

2024-03-13 06:37 UTC, boucadair commented on draft-rwbr-tsvwg-signaling-use-cases.md
> +This document lists uses-cases demonstrating the need for a mechanism
```suggestion
This document lists uses cases demonstrating the need for a mechanism
```

2024-03-13 06:37 UTC, boucadair commented on draft-rwbr-tsvwg-signaling-use-cases.md
> +paper, this is termed 'reactive policy'.
```suggestion
document, this is termed 'reactive policy'.
```

2024-03-13 06:37 UTC, boucadair commented on draft-rwbr-tsvwg-signaling-use-cases.md
> +to discard or delay packets -- which can harm certain flows.  In this
```suggestion
to discard or delay packets -- which can harm certain flows and thus lead to suboptimal perceived experience.  In this
```

2024-03-13 06:37 UTC, boucadair commented on draft-rwbr-tsvwg-signaling-use-cases.md
> +Configured cooperation between an ISP and content providers can allows
```suggestion
Configured cooperation between an ISP and content providers (via contractual agreements, typically) can allow
```

2024-03-13 06:37 UTC, boucadair commented on draft-rwbr-tsvwg-signaling-use-cases.md
> +A more egalitarian approach provides the same benefit ot parties --
```suggestion
A more egalitarian approach provides the same benefit to parties --
```

2024-03-13 06:37 UTC, boucadair commented on draft-rwbr-tsvwg-signaling-use-cases.md
> +content providers, this paper shows use-cases where the client
```suggestion
content providers, this document shows use cases where the client
```

2024-03-13 06:37 UTC, boucadair commented on draft-rwbr-tsvwg-signaling-use-cases.md
> +use-cases to further detail the need of such signaling and highlights
```suggestion
use cases to further detail the need of such signaling and highlights
```

2024-03-13 06:37 UTC, boucadair commented on draft-rwbr-tsvwg-signaling-use-cases.md
> +However, this cooperation favors large Internet service providers and
```suggestion
However, this cooperation might have scalability issues (e.g., ISPs to establish and maintain agreements with a large number of content providers), operational implications as the network configuration will rely on service-specific (e.g., risk of frozen or stale configuration), mismatch between the expected service level from users and the delivered one, etc. 
```

2024-03-13 06:37 UTC, boucadair commented on draft-rwbr-tsvwg-signaling-use-cases.md
> +favors large content providers.  Smaller ISPs, small content
```suggestion
Moreover, smaller ISPs, small content
```

2024-03-13 06:37 UTC, boucadair commented on draft-rwbr-tsvwg-signaling-use-cases.md
> +parties to become part of the "Internet fast lane".
```suggestion
parties to become part of the "Internet fast lane". Also, this approach improves the Internet for end users per {{?RFC8890}}.
```

2024-03-13 15:18 UTC, danwing reviewed
Thanks, Med!

2024-03-13 15:20 UTC, merged

2024-03-13 16:11 UTC, boucadair commented
Is it normal that none of the proposed changes are implemented?

2024-03-14 00:52 UTC, danwing commented
I’ll take a look. I did a bulk commit for first time maybe I did that wrong. -dOn Mar 13, 2024, at 9:11 AM, Med ***@***.***> wrote:﻿
Is it normal that none of the proposed changes are implemented?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>